# Documentation - https://alacritty.org/config-alacritty.html
[window]

opacity = 0.9

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 850

[font]

normal = { family = "0xProto Nerd Font", style = "Regular" }
bold = { family = "0xProto Nerd Font", style = "Bold"}
italic = { family = "0xProto Nerd Font", style = "Italic" }
size = 12

[general]
working_directory = "$HOME"
live_config_reload = true

import = [
# "~/.config/alacritty/themes/monokai-pro.toml"
"~/.config/alacritty/themes/ayu_mirage.toml"
]
